language: python
python:
  - "3.6"
  - "3.7-dev"
  - "pypy3"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y tesseract-ocr tesseract-ocr-eng tesseract-ocr-jpn
install:
  - pip install .
  - pip install -r dev-requirements.txt
script: nosetests
